### ISSUE TITLE
Does not compile on Lazarus stable (2.0.8), not your fault

### ISSUE THREAD

**Issue by gcarreno** [chapmanworld/cwRuntime#9]
Hey Craig,

Just recently I've noticed that the `trunk` version of Lazarus as upgraded the `*.lpi` version to `12`.

This breaks with the stable version of Lazarus, now at `2.0.8`, since it only understands up to version `11` and complains that there is no main unit on the project.

Had a look to see how much work one had to put in to downgrade and it's quite complex. If you want a more complete explanation I can try and muster one, from the 30m I spent investigating the issue.

So you now have some options, IMHO:

- I don't care it's a "you" problem :)
- Won't fix since I'm deliberately using FPC 3.3.x functionality, not back portable.
- Delete the current `src/tests/test_cwRuntime.lpi` and recreate it with an earlier version.
  - If you chose this, will have to repeat for every `*.lpi` on the repo.

Cheers,
Gus

**Comment by chapmanworld** [comment]
Well. This actually is a bit of a conundrum.
I am using functionality that's only available in the FPC trunk (a couple of bug fixes that I submitted tickets for), so I know that the latest compiler is required for the runtime... however, I believe the stable IDE does work with the trunk compiler. 

So I *should* support older lazarus, but may have to set a minimum version for it.
I don't mind setting a minimum version for Lazarus, since anyone can have the latest for free (unlike Delphi), will give it more thought.

**Comment by gcarreno** [comment]
Hi Craig,

What you said about Lazarus 2.0.8 being able to run on FPC trunk never crossed my mind.
I think it didn't because I've been in the mindset of the combos I'm kinda stuck with on sourceforge while developing the GitHub Action [setup-lazarus](https://github.com/gcarreno/setup-lazarus) and the ones you get used to, on fpcupdeluxe.

Let me give you my opinion, probably a bit biased since it comes from the way I'm seeing Lazarus and FPC being packaged:
- Trunk is at Lazarus 2.1.0 FPC 3.3.1
- Below that we have Stable at Lazarus 2.0.8 FPC 3.0.4

Previous to that we get a series of earlier(_historic?_) stable combinations, but it seems the important ones are when the compiler has a stable release, so before FPC 3.0.4 we have:
- Lazarus 1.6.4 FPC 3.0.2
- Lazarus 1.6 FPC 3.0.0
- Lazarus 1.2.2 FPC 2.6.4

And so on.

Coming back to my opinion, If it's not stable, you say trunk, for both, and that's it.

I feel that, now, the community tracks the leaps on pre 3.0.0 and post 3.0.0, since that was the version with namespaces and anything with it, will simply break pre 3.0.0. 
Then those leaps will go through 3.0.2 and 3.0.4, which I'm not really aware of the major advances and what breaks.

After namespacing, I think, in your case, it makes sense stressing the trunk argument since you are using functionality you requested and is only present in trunk. Well, until that gets into a stable release, ofc...

So to conclude this big ranting, with too much sleep depravation, I say you just go for:
- _Won't fix since I'm deliberately using FPC 3.3.x functionality_**(that I asked for)**_, not back portable._

Cheers,
Gus

**Comment by chapmanworld** [comment]
There is actually now only one bug-fix that the cwRuntime uses from FPC 3.3.x and it is used only within the cwVectors.pas unit. Essentially, a vector can be assigned as an array fx...

  Vector := [1,2,3];
  (with the bug in place, the compiler assumes the array of literals is a set)

The vectors functionality is not used elsewhere by the runtime, and so I could offer support for earlier compiler versions by simply disabling those operator overloads in cwVectors, or simply stating that cwVectors will not work pre FPC 3.3.x

The bigger concern for me is the work involved in maintaining multiple project files for different IDE versions.  Doing CI for Delphi has demonstrated how much work this is because not only did I have to install six versions of Delphi concurrently, but I also had to create six versions of every project file, each of which had to be manually edited to share the same .dpr file.

For Delphi, supporting multiple versions is far more important because many customers will only update to the latest version if there's a good reason for spending the $, and as an added aside the differences in IDE and RTL are usually more significant in terms of breaking changes.
The latest version of Lazarus is always available at no cost, and so it becomes less of a concern to support multiple versions. 

Therefore, I think I have a fair compromise solution.
When I can safely call cwRuntime a release version, I'll create two releases.

Version numbering TBD, numbers here as example...

- Release (1.0) - Requires Lazarus 2.0.8 but does not have the cwVectors features, and is not CI tested, (but tested manually) since the bulk of the code is tested against Release 1.1
- Release (1.1) - Minimum requirement for Lazarus trunk + adds back cwVectors features.
- Future releases (post fpc 3.3x support in Lazarus) will relax the minimum requirement from trunk to latest stable.

This way, I only ever have to maintain the latest stable Lazarus IDE project files for the CI server (after the compiler 3.3.x support is met). I can still provide a version in short time for the current stable Lazarus that should be stable.

As an FYI on my to-do list before I create the releases.
1) I'm overhauling parts of the logging system (required for my other projects)
2) I need to get tests in at least for the newly added cwTiming and cwSockets functionality.
3) The documentation needs a solid proofing.
* I'm willing to release before all intended targets are supported, but I have OSX working already.
The actual next stable Lazarus release may happen before I'm done :-/

**Comment by gcarreno** [comment]
Hey @chapmanworld,

Since we're now at `Lazarus 2.0.10` and `FPC 3.2.0` for both stable versions, is this issue now moot?

I don't remember the Rev on `FPC` you mentioned where all your changes were introduced into `FPC`. Did you post it somewhere in the comments above?

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @chapmanworld,

Bah humbug!! Nevermind the above comment. I've just recompiled the latest commit, as of 2020/07/11 12:40 BST, and ran against the real issue: `Lazarus 2.0.10` still does not understand `*.lpi` files of version 12 IIRC.

So carry on, nothing to see here... :stuck_out_tongue_winking_eye: 

Cheers,
Gus

**Comment by chapmanworld** [comment]
After the release of 2.0.10 I had the same issue with some of the .lpi files.

I've also been making some large-scale edits/refactors.
(cwThreading is entirely rewritten, cwLog in progress, and added cwStatus).

I've branched the old stuff off and started an overhaul, which now has a group named grp_cwRuntime_Lazraus_2_0_10, the package is also named after 2.0.10, and the sample projects all got a refit too.

I'll consider going back and adding 2.0.8 project files, but first I need to repair the Delphi projects and groups, and get the CI back up and running (cos I broke that too!)

Anyhow, going forwards I'm going to keep the master branch on the latest stable release of lazarus, at the expense of possibly having to remake all the projects each time *grumbles*.  - Work in progress and I've not fully tested the new threading code on Linux yet - stand-by.
